#pragma config(Motor,  port2,           rightMotor,    tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*   	                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/
void driveForward(int i)
{
	motor[rightMotor] = 127;		  // Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = 127;		  // Motor on port3 is run at full (127) power forward
	wait1Msec(i * 1000);			        // Robot runs previous code for 1000 milliseconds before moving on


}
void stopMotor()
{
		motor[rightMotor] = 0;		  	// Motor on port2 is run at full (0) power Stop
		motor[leftMotor]  = 0;		  	// Motor on port3 is run at full (0) power Stop
		wait1Msec(2000);
}
void driveBackward(int i)
{
		motor[rightMotor] = -127;		  // Motor on port2 is run at full (-127) power reverse
		motor[leftMotor]  = -127;		  // Motor on port3 is run at full (-127) power reverse
		wait1Msec(i * 1000);
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{

	wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program


	for(int i = 1; i <= 5; i++)
	{
		driveForward(i);

		stopMotor();

		driveBackward(i);

		stopMotor();
	}





}												        // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
