#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Forward for Distance with Encoders -                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward for 5 rotations of the left shaft encoder.       *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ummál dekks = 31,9 = 360°																															      *|
|*        50/31,9 = 1,567398119122257																										              *|
|*        360° * 1,567398119122257 = 564          																										*|
|*        																																									          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/
void resetEncoder(){
	SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;
}

void straight(){

}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  wait1Msec(2000);  // 2 Second Delay

  //Clear Encoders
  SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;
	for(int i = 1; i <= 5; i++)
	{

  	while(SensorValue[leftEncoder] < (i*564))
  	{

    	if(SensorValue[rightEncoder] == SensorValue[leftEncoder]) // If rightEncoder has counted the same amount as leftEncoder:
		{
			// Move Forward
			motor[rightMotor] = 80;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 80;		    // Left Motor is run at power level 80
		}
		else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])	// If rightEncoder has counted more encoder counts
		{
			// Turn slightly right
			motor[rightMotor] = 80;		    // Right Motor is run at power level 60
			motor[leftMotor]  = 70;		    // Left Motor is run at power level 80
		}
		else	// Only runs if leftEncoder has counted more encoder counts
		{
			// Turn slightly left
			motor[rightMotor] = 70;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 80;		    // Left Motor is run at power level 60
		}
  	}
		resetEncoder();
  	//...Stop
  	motor[rightMotor] = 0;
    motor[leftMotor] = 0;
    wait1Msec(500);

  	while(SensorValue[rightEncoder] < (i*564))
  	{
    	//...Move Backwards
    	if(SensorValue[rightEncoder] == SensorValue[leftEncoder])
		{
			// Move Backwards
			motor[rightMotor] = -80;
			motor[leftMotor]  = -80;
		}
		else if(SensorValue[rightEncoder] < SensorValue[leftEncoder])
		{
			// Turn slightly left
			motor[rightMotor] = -80;
			motor[leftMotor]  = -70;
		}
		else
		{
			// Turn slightly right
			motor[rightMotor] = -70;
			motor[leftMotor]  = -80;
		}
  	}
  	resetEncoder();
  	//...Stop
  	motor[rightMotor] = 0;
    motor[leftMotor] = 0;
    wait1Msec(500);



	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
