#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Forward for Distance with Encoders -                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward for 5 rotations of the left shaft encoder.       *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  1027 is 360 rotation
*|				WHELEBASE = 1027/360 1 deg
|*        "Squarebot" model, but may not be needed for all robot configurations.                      *|
|*    2)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/
/*void resetEncoder(){
SensorValue[rightEncoder] = 0;
SensorValue[leftEncoder] = 0;
}*/
const float WHEELBASE = 2.4;

void reset()
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
}

void forward()
{
	while(abs(SensorValue[leftEncoder]) < 564 && vexRT[Btn8D] != 1) // While the right encoder is less than distance:
	{
		motor[rightMotor] = 60;		  // Motor on port2 is run at full (60) power reverse
		motor[leftMotor]  = 60;		  // Motor on port3 is run at full (60) power
	}
}
void left(int deg)
{
	while(abs(SensorValue[leftEncoder]) < deg * WHEELBASE && vexRT[Btn8D] != 1) // While the right encoder is less than distance:
	{
		motor[rightMotor] = -60;		  // Motor on port2 is run at full (-60) power reverse
		motor[leftMotor]  = 60;		  // Motor on port3 is run at full (60) power
	}
}
void right(int deg)
{
	while(abs(SensorValue[leftEncoder]) < deg * WHEELBASE && vexRT[Btn8D] != 1) // While the right encoder is less than distance:
	{
		motor[rightMotor] = 60;		  // Motor on port2 is run at full (60) power reverse
		motor[leftMotor]  = -60;		  // Motor on port3 is run at full (-60) power
	}
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++


task main()
{

	reset();
	forward();
	reset();


	left(90);
	reset();

	forward();
	reset();

	right(130);
	reset();

	forward();
	reset();

	right(130);
	reset();

	forward();
	reset();

}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
